name: Build and Test Client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./client/...

    - name: Test
      run: go test -v ./client/...

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: ./client
        args: -E gofmt --max-same-issues 0
