name: Build and Test Signer Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version: 1.26

    - name: Build
      working-directory: ./internal/signer/windows
      run: go build -v ./...

    - name: Test
      working-directory: ./internal/signer/windows
      run: go test -v ./...
      
    - name: Lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        version: latest
        working-directory: ./internal/signer/windows
        args: --max-same-issues 0

    - name: Create Binaries
      run: .\build\scripts\windows_amd64.ps1

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: windows_amd64
        path: .\build\bin\windows_amd64\*
