name: Build and Test Signer Darwin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: 1.26

    - name: Build
      working-directory: ./internal/signer/darwin
      run: go build -v ./...

      # The binary must be built before creating credentials so it can be added
      # as a trusted application to the keychain.
    - name: Build Test Binary for Signer
      working-directory: ./internal/signer/darwin/keychain
      run: go test -c .

    - name: Create keychain credentials
      run: ./scripts/keychain_cred.sh
      
    - name: Run Test Binary for Signer
      working-directory: ./internal/signer/darwin/keychain
      run: ./keychain.test

    - name: Test Darwin Client
      working-directory: ./darwin
      run: go test -v .
      
    - name: Lint Signer
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        version: latest
        working-directory: ./internal/signer/darwin
        args: --max-same-issues 0

    - name: Lint Client
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        version: latest
        working-directory: ./darwin
        args: --max-same-issues 0

    - name: Create Binaries
      run: ./build/scripts/darwin_amd64.sh && ./build/scripts/darwin_arm64.sh

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: darwin_amd64
        path: ./build/bin/darwin_amd64/*

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: darwin_arm64
        path: ./build/bin/darwin_arm64/*
